name: CI for booking.com

on:
  workflow_dispatch

jobs:
  
  frontend-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: npm install and test UI
        run: |
          npm install
          npm test